### ISSUE TITLE
Uc分享的图片

### ISSUE THREAD

**Issue by felemon** [JefferyWang/nativeShare.js#2]
您好，分享时发现UC分享到站外的图片是屏幕的截图，不是传的图片，代码中的title改为img仍然无效，怎么破？
![qq 20150623151423](https://cloud.githubusercontent.com/assets/4068351/8300756/ba1b70d6-19ba-11e5-9fc7-460bf1782948.png)

**Comment by jefferywang** [comment]
这个是UC浏览器内部分享图片现在都是所在屏幕截图,暂时无法解决.

**Comment by felemon** [comment]
了解了，多谢！
