### ISSUE TITLE
测了下，代码在UC上目前有点问题

### ISSUE THREAD

**Issue by AngusFu** [JefferyWang/nativeShare.js#4]
![image](https://cloud.githubusercontent.com/assets/8180186/8821566/3c749d22-3091-11e5-8754-5b7376222310.png)
主要问题在这里。。。
UC上面，分享到微信，是需要根据平台来决定的。然而现在的代码中仅仅只定义了ios下面的分享名称。

ios: kWeixin || kWeixinFriend;
android: WechatFriends || WechatTimeline

我也是看了segmentFault上然后打算自己写的。之前写了一版，不满意，昨天准备再写，然后就发现了这个github上的。

**Comment by jefferywang** [comment]
嗯嗯，之前也有人反馈安卓有问题，不过因为自己没安卓手机，所以没办法测试，抽空会修改一下

**Comment by jefferywang** [comment]
目前已修复
